const sampleData = {
  allOrNothing: true,
  avatarUrl: 'https://s3.amazonaws.com/jumpstarter-pics/headshot85.jpg',
  category: 'Tools',
  city: 'East Jake',
  commentsCount: 9,
  country: 'VI',
  createdAt: '2016-02-13T13:44:54.000Z',
  creatorId: 349,
  description: 'Est odio consequuntur perferendis ut quam. Ab voluptatem molestiae sint totam voluptatem. Occaecati sit reprehenderit quidem distinctio est ad nobis eius. Voluptates ducimus dolores architecto nihil autem qui dolorem aliquam quia.',
  endDate: '2018-11-14T00:47:47.000Z',
  faqsCount: 0,
  firstName: 'Raven',
  goalAmt: '96222',
  id: 42,
  imageUrl: 'https://s3.amazonaws.com/jumpstarter-pics/product24.jpg',
  lastName: 'Wolf',
  pledgesCount: 12,
  projectsCreatedCount: 1,
  state: 'North Carolina',
  title: 'Practical Cotton Bacon',
  totalPledgeAmt: '7961',
  updatesCount: 4,
};

export default sampleData;
